apiVersion: v1
kind: Secret
metadata:
  name: activemq-creds
  namespace: NAMESPACE
type: Opaque
stringData:
  username: banka
  password: banka1234
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
  namespace: NAMESPACE
  labels:
    app: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
        - image: docker.io/vromero/activemq-artemis:latest-alpine
          name: activemq-artemis
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
          ports:
            - name: activemq
              containerPort: 61616
          env:
            - name: ARTEMIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: activemq-creds
                  key: username
                  optional: false
            - name: ARTEMIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: activemq-creds
                  key: password
                  optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: activemq
  namespace: NAMESPACE
  labels:
    app: activemq
spec:
  selector:
    app: activemq
  ports:
    - port: 61616
      protocol: TCP
      targetPort: activemq
