apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
  namespace: banka-dev
  labels:
    app: mail-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-service
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
        - image: ghcr.io/raf-si-2021/banka-mail-service:latest
          name: banka-mail-service
          imagePullPolicy: Always
          resources: 
            limits:
              cpu: "1"
              memory: 1Gi
          ports:
            - name: mail-service
              containerPort: 8081
          env:
            - name: "spring.mail.username"
              valueFrom: 
                secretKeyRef: 
                  name: email-creds
                  key: username
                  optional: false
            - name: "spring.mail.password"
              valueFrom: 
                secretKeyRef: 
                  name: email-creds
                  key: password
                  optional: false
            - name: "spring.activemq.broker-url"
              value: "tcp://activemq:61616"
---
apiVersion: v1
kind: Service
metadata:
  name: mail-service
  namespace: banka-dev
  labels:
    app: mail-service
spec:
  selector:
    app: mail-service
  ports:
    - port: 8081
      protocol: TCP
      targetPort: mail-service
