apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-service
  name: user-service
  namespace: banka-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - image: ghcr.io/raf-si-2021/banka-user-service:latest
        name: banka-user-service
        imagePullPolicy: Always
        resources: 
          limits:
            cpu: 1
            memory: 1Gi
        env:
          - name: 'spring.datasource.hikari.jdbcUrl'
            value: 'jdbc:postgresql://banka-pgbouncer:5432/user'
          - name: 'spring.datasource.hikari.username'
            value: 'admin'
          - name: 'spring.datasource.hikari.password'
            valueFrom: 
              secretKeyRef: 
                name: banka-pguser-admin
                key: password
                optional: false 

---

apiVersion: v1
kind: Service
metadata:
  namespace: banka-dev
  labels:
    app: user-service
  name: user-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: user-service